# Generated by Django 5.1.6 on 2025-02-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
