# Generated by Django 5.1.6 on 2025-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_commande_produits_alter_produit_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom_client',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
