# Generated by Django 5.1.6 on 2025-03-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_retourcommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
