# Generated by Django 5.1.6 on 2025-03-07 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0012_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('telephone', 'Téléphones'), ('cosmetique', 'Cosmétiques'), ('alimentaire', 'Alimentaire')], default='informatique', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
